<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid menu">
		<a class="navbar-brand" href="#">
			<img src="/img/twitter_logo.png" class="menuIco" />
		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="menuItem nav-link" href="/timeline" style="color: #1DA1F2;">
						Home
					</a>
				</li>
				<li class="nav-item">
					<a class="menuItem nav-link" href="/sair" style="color: #1DA1F2;">
						Sair
					</a>
				</li>
				<li class="nav-item">
					<a class="menuItem nav-link" href="/quem_seguir" style="color: #1DA1F2;">
						Procurar mais pessoas
					</a>
				</li>
			</ul>
		</div>
	</div>
</nav>


<!--
<nav class=" navbar navbar-expand-lg menu">
	<div class=" collapse navbar-collapse container-fluid">
		<div class="collapse navbar-collapse navbar-nav">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="menuItem" href="/timeline">
						Home
					</a>
				</li>
				<li class="nav-item">
					<a class="menuItem" href="/sair">
						Sair
					</a>
				</li>
				<img src="/img/twitter_logo.png" class="menuIco" />
			</ul>
		</div>
	</div>
</nav>
-->
<div class="container mt-5">
	<div class="row pt-2">

		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">

					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">
								<?= $this->view->info_usuario['nome'] ?>
							</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_tweets_usuario['total_tweet'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguindo_usuario['total_seguindo'] ?>
							</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">
								<?= $this->view->total_seguidores_usuario['total_seguidores'] ?>
							</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form method="post" action="/tweet">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>

						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>
			<?php foreach ($this->view->tweets as $id_tweet => $tweet) { ?>
				<div class="row tweet">
					<div class="col">
						<p>
							<strong>
								<?= $tweet['nome'] ?>
							</strong>
							<small>
								<span class="text text-muted">- <?= $tweet['data'] ?></span>
							</small>
						</p>
						<p><?= $tweet['tweet'] ?></p>

						<br />
						<?php if ($tweet['id_usuario'] == $_SESSION['id']) { ?>
							<form>
								<div class="col d-flex justify-content-end">
									<a href="/tweet_remover?id=<?= $tweet['id'] ?>" class="btn btn-danger"><small>Remover</small></a>
								</div>
							</form>
						<?php } ?>
					</div>
				</div>
			<?php } ?>
		</div>

		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>